# Generated by Django 6.0.5 on 2026-05-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="descripcion",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción de la empresa"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sitio_web",
            field=models.URLField(blank=True, null=True, verbose_name="Sitio web"),
        ),
        migrations.AddField(
            model_name="user",
            name="ubicacion",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Ubicación/Ciudad"
            ),
        ),
    ]
