# Generated by Django 5.2.4 on 2026-05-06 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("vista", "Vista"),
                            ("click_whatsapp", "Click en WhatsApp"),
                            ("compartir", "Compartir"),
                            ("contacto", "Contacto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interacciones",
                        to="products.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interacciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interacción",
                "verbose_name_plural": "Interacciones",
                "db_table": "interacciones",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["producto", "tipo"],
                        name="interaccion_product_c0788d_idx",
                    ),
                    models.Index(
                        fields=["-fecha"], name="interaccion_fecha_718ec3_idx"
                    ),
                ],
            },
        ),
    ]
