# Generated by Django 5.2.4 on 2026-05-06 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departamento",
                    models.CharField(max_length=100, verbose_name="Departamento"),
                ),
                (
                    "municipio",
                    models.CharField(max_length=100, verbose_name="Municipio"),
                ),
                (
                    "latitud",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación",
                "verbose_name_plural": "Ubicaciones",
                "db_table": "ubicaciones",
                "ordering": ["departamento", "municipio"],
                "unique_together": {("departamento", "municipio")},
            },
        ),
        migrations.CreateModel(
            name="ProveedorUbicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False, verbose_name="Ubicación principal"
                    ),
                ),
                (
                    "direccion_detallada",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dirección detallada"
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        limit_choices_to={"rol": "proveedor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ubicaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ubicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proveedores",
                        to="locations.ubicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación de proveedor",
                "verbose_name_plural": "Ubicaciones de proveedores",
                "db_table": "proveedor_ubicaciones",
                "unique_together": {("proveedor", "ubicacion")},
            },
        ),
    ]
