# Generated by Django 5.2.4 on 2026-05-06 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "db_table": "etiquetas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del producto"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "descripcion_corta",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio"
                    ),
                ),
                (
                    "precio_oferta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="Stock")),
                (
                    "unidad_medida",
                    models.CharField(
                        default="unidad", max_length=50, verbose_name="Unidad de medida"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("pendiente", "Pendiente"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("visitas", models.IntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="categories.categoria",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        limit_choices_to={"rol": "proveedor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ubicacion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="locations.ubicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "productos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ImagenProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.ImageField(
                        upload_to="productos/", verbose_name="URL de la imagen"
                    ),
                ),
                (
                    "es_principal",
                    models.BooleanField(default=False, verbose_name="Imagen principal"),
                ),
                ("orden", models.IntegerField(default=0)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="products.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de producto",
                "verbose_name_plural": "Imágenes de producto",
                "db_table": "imagenes_producto",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="ProductoPatrocinado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de fin")),
                ("activo", models.BooleanField(default=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patrocinios",
                        to="products.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto patrocinado",
                "verbose_name_plural": "Productos patrocinados",
                "db_table": "productos_patrocinados",
            },
        ),
        migrations.CreateModel(
            name="ProductoEtiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etiqueta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_rel",
                        to="products.etiqueta",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etiquetas_rel",
                        to="products.producto",
                    ),
                ),
            ],
            options={
                "db_table": "producto_etiquetas",
                "unique_together": {("producto", "etiqueta")},
            },
        ),
    ]
